name: Export Secret to Artifact

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON file
        run: |
          echo '${{ secrets.YOUR_FB_SECRET_NAME }}' > tokens.json
        
      - name: Upload JSON as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fb-tokens
          path: tokens.json
          retention-days: 1 # Automatically deletes it quickly for safety
